import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const root=path.dirname(fileURLToPath(import.meta.url)),require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/dp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const target=process.env.TARGET_URL||pathToFileURL(path.join(root,'index.html')).href;
const context=await browser.newContext({viewport:{width:1600,height:1100},reducedMotion:'reduce',locale:'en-US',acceptDownloads:true});const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));if(!process.env.TARGET_URL)await context.route(/^https?:/,r=>{requests.push(r.request().url());return r.abort()});
const check=(v,m)=>{if(!v)throw new Error(m)};const waitFrame=async()=>{await page.waitForTimeout(230)};
try{
 await page.goto(target);await page.waitForFunction(()=>window.quietTown);await page.waitForTimeout(800);
 check(await page.locator('html').getAttribute('lang')==='zh-CN','Chinese default failed');check((await page.locator('#scene canvas').count())===1,'Canvas missing');check(!(await page.evaluate(()=>quietTown.getState().motion)),'Reduced motion ignored');
 await page.screenshot({path:path.join(root,'previews','desktop.png')});
 const scenePng=await page.locator('#scene canvas').screenshot();fs.writeFileSync(path.join(root,'previews','town.png'),scenePng);
 for(const id of ['home','post','library']){
  await page.locator(`[data-building=${id}]`).focus();await page.keyboard.press('Enter');await waitFrame();check((await page.evaluate(()=>quietTown.getState())).focused===id,'Building focus '+id);check(await page.locator('#building-panel').isVisible(),'Panel missing '+id);
  await page.locator('#enter').click();await waitFrame();const state=await page.evaluate(()=>quietTown.getState());check(state.opened&&!state.moving,'Interior/reduced-motion arrival '+id);check(await page.evaluate(id=>!quietTown.buildings.find(b=>b.id===id).shell.visible,id),'Shell still visible '+id);await page.screenshot({path:path.join(root,'previews',id+'-interior.png')});
  await page.locator('#building-action').click();check(await page.locator('#paper').isVisible(),'Useful action '+id);await page.keyboard.press('Escape');await page.locator('#close-building').click();await waitFrame();
 }
 await page.locator('#dusk').click();await waitFrame();check((await page.evaluate(()=>quietTown.getState())).night===1,'Dusk failed');await page.screenshot({path:path.join(root,'previews','dusk.png')});await page.locator('#day').click();
 await page.locator('#capture').click();await page.locator('#thought').fill('窗边读了两页书。');await page.locator('#save-thought').click();await page.locator('#things-tab').click();check((await page.locator('.note-list').innerText()).includes('窗边读了两页书。'),'Note not listed');await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>window.quietTown);await page.locator('#things-tab').click();check((await page.locator('.note-list').innerText()).includes('窗边读了两页书。'),'Note not persisted');await page.keyboard.press('Escape');
 await page.locator('#language').click();check(await page.locator('html').getAttribute('lang')==='en','English toggle');await page.locator('#mail-tab').click();check((await page.locator('#paper-title').textContent()).includes('letter'),'English letter');await page.keyboard.press('Escape');await page.locator('#capture').click();await page.locator('#thought').fill('<img src=x onerror=alert(1)>');await page.locator('#save-thought').click();await page.locator('#things-tab').click();check(await page.locator('.note-list img').count()===0,'Notes must be plain text');await page.keyboard.press('Escape');
 await page.locator('#language').click();await page.waitForTimeout(2600);
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});await waitFrame();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow '+width);await page.screenshot({path:path.join(root,'previews',`mobile-${width}.png`)});
  await page.locator('[data-building=home]').click();await page.locator('#enter').click();await waitFrame();await page.screenshot({path:path.join(root,'previews',`mobile-home-${width}.png`)});check(await page.locator('#building-panel').evaluate(el=>el.getBoundingClientRect().right<=innerWidth&&el.getBoundingClientRect().left>=0),'Panel overflow '+width);await page.locator('#close-building').click();
 }
 await page.setViewportSize({width:1600,height:1100});await page.locator('#motion').click();await page.locator('[data-building=post]').click();check((await page.evaluate(()=>quietTown.getState())).moving,'Bean walk did not start');await page.waitForFunction(()=>!quietTown.getState().moving,{},{timeout:12000});await page.locator('#enter').click();await page.waitForFunction(()=>!quietTown.getState().moving,{},{timeout:10000});check((await page.evaluate(()=>quietTown.getState())).opened,'Walking entry failed');await page.locator('#motion').click();await page.locator('#close-building').click();
 await page.locator('#about').click();const dl=page.waitForEvent('download');await page.locator('#export-image').click();const d=await dl;check((await fs.promises.stat(await d.path())).size>10000,'Empty image export');await page.keyboard.press('Escape');
 check(!errors.length,errors.join('\n'));check(!requests.length,'Offline scene requested network');
 const report={target,defaultLanguage:'zh-CN',buildings:3,interiors:3,dayDusk:'passed',notesPersistence:'passed',plainTextNotes:'passed',motionAndArrival:'passed',reducedMotion:'passed',languages:['zh-CN','en'],phoneWidths:[390,320],imageExport:'passed',offlineRequests:requests.length,browserErrors:errors,nativePerformance:'untested'};fs.writeFileSync(path.join(root,'previews',process.env.TARGET_URL?'live-verification.json':'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
}finally{await browser.close()}
